[package]
name = "katana-rs"
authors = ["Chris Franssens"]
version = "0.0.1"
edition = "2021"

[dependencies]
arrayfire = "3.8.0"
lazycell = "1.3.0"

[lib]
name = "katana"
path = "src/lib.rs"

[[example]]
name = "feedforward"
path = "examples/feedforward.rs"